module Teams
  VIRGINIA = 'Virginia'.freeze
  VILLANOVA = 'Villanova'.freeze
  DUKE = 'Duke'.freeze
  CINCINNATI = 'Cincinnati'.freeze
  PURDUE = 'Purdue'.freeze
  MICHIGAN_ST = 'Michigan St.'.freeze
  NORTH_CAROLINA = 'North Carolina'.freeze
  GONZAGA = 'Gonzaga'.freeze
  KANSAS = 'Kansas'.freeze
  MICHIGAN = 'Michigan'.freeze
  TENNESSEE = 'Tennessee'.freeze
  TEXAS_TECH = 'Texas Tech'.freeze
  WEST_VIRGINIA = 'West Virginia'.freeze
  XAVIER = 'Xavier'.freeze
  OHIO_ST = 'Ohio St.'.freeze
  AUBURN = 'Auburn'.freeze
  HOUSTON = 'Houston'.freeze
  KENTUCKY = 'Kentucky'.freeze
  CLEMSON = 'Clemson'.freeze
  WICHITA_ST = 'Wichita St.'.freeze
  ARIZONA = 'Arizona'.freeze
  TCU = 'TCU'.freeze
  FLORIDA = 'Florida'.freeze
  NEVADA = 'Nevada'.freeze
  BUTLER = 'Butler'.freeze
  SETON_HALL = 'Seton Hall'.freeze
  CREIGHTON = 'Creighton'.freeze
  TEXAS_A_M = 'Texas A&M'.freeze
  VIRGINIA_TECH = 'Virginia Tech'.freeze
  FLORIDA_ST = 'Florida St.'.freeze
  MIAMI_FL = 'Miami FL'.freeze
  ARKANSAS = 'Arkansas'.freeze
  MISSOURI = 'Missouri'.freeze
  TEXAS = 'Texas'.freeze
  NORTH_CAROLINA_ST = 'North Carolina St.'.freeze
  LOYOLA_CHICAGO = 'Loyola Chicago'.freeze
  DAVIDSON = 'Davidson'.freeze
  KANSAS_ST = 'Kansas St.'.freeze
  ARIZONA_ST = 'Arizona St.'.freeze
  OKLAHOMA = 'Oklahoma'.freeze
  RHODE_ISLAND = 'Rhode Island'.freeze
  UCLA = 'UCLA'.freeze
  SAN_DIEGO_ST = 'San Diego St.'.freeze
  ALABAMA = 'Alabama'.freeze
  SYRACUSE = 'Syracuse'.freeze
  NEW_MEXICO_ST = 'New Mexico St.'.freeze
  MURRAY_ST = 'Murray St.'.freeze
  PROVIDENCE = 'Providence'.freeze
  ST_BONAVENTURE = 'St. Bonaventure'.freeze
  MONTANA = 'Montana'.freeze
  BUFFALO = 'Buffalo'.freeze
  SOUTH_DAKOTA_ST = 'South Dakota St.'.freeze
  UNC_GREENSBORO = 'UNC Greensboro'.freeze
  GEORGIA_ST = 'Georgia St.'.freeze
  BUCKNELL = 'Bucknell'.freeze
  STEPHEN_F_AUSTIN = 'Stephen F. Austin'.freeze
  MARSHALL = 'Marshall'.freeze
  COLLEGE_OF_CHARLESTON = 'College of Charleston'.freeze
  PENN = 'Penn'.freeze
  IONA = 'Iona'.freeze
  WRIGHT_ST = 'Wright St.'.freeze
  CAL_ST_FULLERTON = 'Cal St. Fullerton'.freeze
  LIPSCOMB = 'Lipscomb'.freeze
  RADFORD = 'Radford'.freeze
  UMBC = 'UMBC'.freeze
  TEXAS_SOUTHERN = 'Texas Southern'.freeze
  LIU_BROOKLYN = 'LIU Brooklyn'.freeze
  NORTH_CAROLINA_CENTRAL = 'North Carolina Central'.freeze
end
